Add missing DEVICE_TRNG flags for psa_hrng.c
This file depends on trng_t which is behind DEVICE_TRNG to allow compilation with device without TRNG.

Fixes compilation errors:

[Error] psa_hrng.c@22,26: unknown type name 'trng_t'
[Error] psa_hrng.c@28,26: unknown type name 'trng_t'
[Error] psa_hrng.c@33,30: unknown type name 'trng_t'
[ERROR] ./mbed-os/features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/src/psa_hrng.c:22:26: error: unknown type name 'trng_t'
   22 | MBED_WEAK void trng_init(trng_t *obj)
      |                          ^~~~~~
./mbed-os/features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/src/psa_hrng.c:28:26: error: unknown type name 'trng_t'
   28 | MBED_WEAK void trng_free(trng_t *obj)
      |                          ^~~~~~
./mbed-os/features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/src/psa_hrng.c:33:30: error: unknown type name 'trng_t'
   33 | MBED_WEAK int trng_get_bytes(trng_t *obj, uint8_t *output, size_t length, size_t *output_length)
      |